name: Bandit Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin -y

      - name: Build Docker image
        run: docker compose build

      - name: Run Bandit scan
        run: docker compose run bandit

      - name: Clean up
        run: docker compose down