name: Bandit Security Scan

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin -y

      - name: Build Docker image
        run: docker compose build app

      - name: Run Bandit scan inside app container
        run: docker compose run app /app/venv/bin/bandit -r /app

      - name: Clean up
        run: docker compose down