version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - rnpesr
  bandit:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/venv/bin/bandit -r /app
    networks:
      - rnpesr
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rnpesr
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rnpesr
  #zap:
  #  image: ghcr.io/zaproxy/zaproxy:stable
  #  volumes:
  #    - zap_data:/zap/wrk
  #    - ./relatorios:/zap/wrk
  #    - ./relatorios/zap:/zap/wrk
  #  command: ["zap-baseline.py", "-t", "http://app:5000"]
  #  networks:
  #    - rnpesr
  #  user: "1000:1000"  # Define UID e GID para o contêiner
  #  depends_on:
  #    - app

networks:
  rnpesr:
    driver: bridge

volumes:
  grafana_data:
  zap_data: