global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'bandit'
    static_configs:
      - targets: ['bandit:5000']  # Ajuste a porta se necessário