name: Trivy - SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Adicionando rastreabilidade
      - name: Generate timestamp
        id: timestamp
        run: echo "now=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.now }}

      # Executar o scaner e produzir o relat처rio
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ env.now }}"
          format: "table"
          output: "./trivy-report.txt"
          exit-code: "0"  # N찾o falhar mesmo se encontrar vulnerabilidades
          severity: "CRITICAL,HIGH" # Apenas vulnerabilidade Critica e Alta

      # Fazer upload do relat처rio e disponibilizar no Artifacts
      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy-report.txt 

      # Chamar a pr처xima pipeline
      - name: Dependency Check
        run: |
          gh workflow run DependenciasZap.yml
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}