name: Dependency Check - SAST

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Executar o scaner e produzir o relatório
      - name: Run OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.2/dependency-check-6.5.2-release.zip
          unzip dependency-check.zip -d dependency-check
          
          # Descobre o caminho correto do script
          SCRIPT_PATH=$(find dependency-check -type f -name "dependency-check.sh" | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "Script dependency-check.sh não encontrado!"
            exit 1
          fi

          chmod +x "$SCRIPT_PATH"

          "$SCRIPT_PATH" \
            --project "DecSecOps" \
            --scan . \
            --format "ALL" \
            --out ./dependency-check-report \
            --exclude "external_libs/**,*.dll" \
            --disableAssembly

      # Fazer upload do relatório e disponibilizar no Artifacts
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report

      # Chamar a próxima pipeline
      - name: Trigger Bandit - SAST
        run: |
          gh workflow run Bandit.yaml
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}