name: Bandit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Construir os serviços definidos no docker-compose.yml
      - name: Build Services
        run: docker-compose build

      # Executar o Bandit scan e salvar o relatório
      - name: Run Bandit scan
        run: docker compose run bandit /app/venv/bin/bandit -r /app -c /app/.bandit -f json -o /app/reports/bandit-report.json
        continue-on-error: true

      # Fazer upload do relatório como artefato
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: app/reports/bandit-report.json

      # Parar os serviços com Docker Compose
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
