name: OWASP Dependency-Check Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Dependency-Check
        uses: jeremylong/DependencyCheck_Action@v3
        with:
          scan_path: .
          format: ALL
          output_directory: './dependency-check-report'
      
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ./dependency-check-report