name: Dependency Check - SAST

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout do c贸digo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Executar o scaner e produzir o relat贸rio
      - name: Run OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.2/dependency-check-6.5.2-release.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh
          dependency-check/bin/dependency-check.sh \
            --project "DecSecOps" \
            --scan . \
            --format "ALL" \
            --out ./dependency-check-report \
            --exclude "external_libs/**" \
            --exclude "*.dll" \
            --disableAssembly

      # Fazer upload do relat贸rio e disponibilizar no Artifacts
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report

      # Chamar a pr贸xima pipeline
      - name: Trigger Bandit - SAST
        run: |
          gh workflow run Bandit.yaml
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}