name: Dependency Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Instalar OWASP Dependency-Check CLI e executar análise
      - name: Run OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-6.5.2-release.zip
          unzip dependency-check.zip -d dependency-check
          dependency-check/bin/dependency-check.sh --project "DecSecOps" --scan . --format "ALL" --out ./dependency-check-report

      # Upload do relatório
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./dependency-check-report
    