name: Dependency Check for DecSecOps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Substitua pela versão de Python utilizada no projeto

      # Etapa 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Etapa 4: Instalar OWASP Dependency-Check CLI
      - name: Install OWASP Dependency-Check CLI
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-6.5.2-release.zip
          unzip dependency-check.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      # Etapa 5: Executar o Dependency-Check
      - name: Run Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh \
            --project "DecSecOps" \
            --scan . \
            --format "ALL" \
            --out ./dependency-check-report

      # Etapa 6: Fazer upload do relatório
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3.1.3 #Versão especifica da action
        with:
          name: dependency-check-report
          path: ./dependency-check-report