name: Dependency Check for DecSecOps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' # Substitua pela versão de Python utilizada no projeto

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install OWASP Dependency-Check CLI
      run: |
        curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check-6.5.2-release.zip
        unzip dependency-check.zip -d dependency-check
        chmod +x dependency-check/bin/dependency-check.sh

    - name: Run Dependency-Check
      run: |
        dependency-check/bin/dependency-check.sh \
          --project "DecSecOps" \
          --scan . \
          --format "ALL" \
          --out ./dependency-check-report

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ./dependency-check-report