name: Docker Image CI com Trivy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date +%s)"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ steps.timestamp.outputs.now }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ steps.timestamp.outputs.now }}"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH" # Verifica apenas falhas CRITICAL e HIGH
          ignore-policy: "./app/trivy-ignore.yaml"