name: Trivy - SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Generate timestamp
        id: timestamp
        run: echo "now=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.now }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ env.now }}"
          format: "table"
          output: "./trivy-report.txt"  # Certifique-se do caminho completo
          exit-code: "0"  # Não falhar mesmo se encontrar vulnerabilidades
          severity: "CRITICAL,HIGH"

      - name: List generated files
        run: ls -la  # Para verificar onde o arquivo foi gerado

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./trivy-report.txt  # Caminho completo para o arquivo