name: Trivy - SAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=now::$(date +%s)"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ steps.timestamp.outputs.now }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ steps.timestamp.outputs.now }}"
          format: "table"
          exit-code: "0"
          severity: "CRITICAL,HIGH"
          #trivyignores: "./trivyignore.yaml"

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt

      - name: Dependency Check
        run: |
          gh workflow run DependenciasZap.yml
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}