name: ZAP Security Scan DAST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose
        run: docker-compose up -d --build

      - name: Run ZAP Scan
        run: |
          mkdir -p ./relatorios/zap
          docker run --rm --user root --network=decsecops_rnpesr --name zap-scan \
            -v $(pwd)/relatorios/zap:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable bash -c "
              zap-baseline.py -t http://app:5000 -r /zap/wrk/zap_report.html -I -d --autooff &&
              if [ -f /zap/wrk/zap_report.html ]; then
                echo 'Relatório gerado com sucesso!';
              else
                echo 'Erro: Relatório não encontrado!';
                exit 1;
              fi"

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Report
          path: ./relatorios/zap/zap_report.html

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
