name: ZAP Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Etapa 2: Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Etapa 3: Iniciar os serviços com Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d --build

      # Etapa 4: Executar o ZAP Scan (sem relatório)
      - name: Run ZAP Scan
        run: |
          docker exec $(docker ps -qf "name=zap") zap-baseline.py \
          -t http://app:5000

      # Etapa 5: Parar os serviços com Docker Compose
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down