name: ZAP Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Instalar Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Subir os serviços com Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d --build

      # Verificar se o container do app está rodando
      - name: Verify App Container
        run: docker ps -a

      # Aguardar o serviço "app" ficar acessível
      - name: Wait for App to be Ready
        run: |
          echo "Aguardando o serviço app estar acessível..."
          for i in {1..10}; do
            if docker exec $(docker ps -qf "name=app") curl -s http://app:5000; then
              echo "Serviço disponível!"
              break
            fi
            echo "Tentativa $i: Serviço ainda não está acessível, aguardando..."
            sleep 5
          done

      # Adicionar um tempo para garantir que os serviços estejam prontos
      - name: Sleep before ZAP
        run: sleep 30

      # Executar o ZAP Scan diretamente na mesma rede do Docker Compose
      - name: Run ZAP Scan
        run: |
          mkdir -p ./relatorios/zap
          docker run --rm --user root --network=$(docker network ls --format '{{.Name}}' | grep _default) --name zap-scan \
            -v $(pwd)/relatorios/zap:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable bash -c "apt-get update && apt-get install -y dnsutils && sleep 5 && nslookup app && curl -s http://app:5000 && zap-baseline.py -t http://app:5000 -r /zap/wrk/report.html"
        continue-on-error: true

      # Publicar o relatório HTML como artefato do GitHub Actions
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP Report
          path: ./relatorios/zap/report.html
        if: always()

      # Parar os serviços com Docker Compose
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
