name: ZAP Security Scan - DAST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

#      - name: Install Docker Compose
#        run: |
#          curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          chmod +x /usr/local/bin/docker-compose
#          docker-compose version

#      - name: Start Docker Compose
#        run: docker-compose up -d --build

      - name: Run ZAP Scan
        run: |
          docker run --rm --user root --network=decsecops_rnpesr --name zap-scan \
            -v $(pwd)/relatorios/zap:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable bash -c "
              apt-get update &&
              zap-baseline.py -t http://app:5000 -I"

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down